### PR TITLE
Create CODEOWNERS

### PR DESCRIPTION
**Pull request by tig567899**
@pkrshnan @firemaster1294 Do we want this?

### CODE REVIEW

**Comment by firemaster1294** [comment]
What will this do?

**Comment by tig567899** [comment]
All PRs that go into this repository will require at least one codeowner to approve before merging

**Comment by pkrshnan** [comment]
It'll be similar to what we have right now, except that only the people listed in this file can actually approve, not just collaborators.

**Comment by tig567899** [comment]
Closing this as the number of collaborators we have isn't large enough to justify something this rigid.

**Pull request closed without merging**
