### PR TITLE
Faction modification page

### LINKED ISSUE #11: Faction modification page?
Currently the necro needs to go into backend to do this. This sucks. Let's change this?

### PR DESCRIPTION
**Pull request by pkrshnan**
Fixes #11 

Changes:
- Added ability to change/remove a player's faction
- Added ability to create/edit factions and add new modifiers
- Added ability to delete factions/modifiers
- Copy of Player list now exists on faction page

image

### CODE REVIEW

**Comment by pkrshnan** [comment]
> get_players includes their shop score. Maybe you don’t intend for it to work like this?

I do infact intend for that to happen. The reason being that if add one time bonuses to factions, it'll show up in the scores!

**Comment by pkrshnan** [comment]
> What’s with the try statements?

When you call `Faction.objects.get()`, if it finds one with an invalid id, it will throw an error instead of simply return a None object. Some of them are to handle that case.

Other ones are meant for in the case that there are validation errors on the Model level when attempting to save a faction.

**Comment by pkrshnan** [comment]
> Do we want players to be able to update factions their own if allowed by the Necro?

Maybe? This adds a bunch of complexity around what specifically is allowed and what is not. I'd rather have a moderator only change it since then the player is required to come to the Shop in order to update their faction. This might also allow the mods to do any special actions they might need to do that are associated with registering the player in the faction.

That being said, I'm open to changing this!

**Review by tig567899 — APPROVED** [review]

**Comment by tig567899** [comment]
> 
> 
> > Do we want players to be able to update factions their own if allowed by the Necro?
> 
> Maybe? This adds a bunch of complexity around what specifically is allowed and what is not. I'd rather have a moderator only change it since then the player is required to come to the Shop in order to update their faction. This might also allow the mods to do any special actions they might need to do that are associated with registering the player in the faction.
> 
> That being said, I'm open to changing this!

Allowing players to change factions could open it up to abuse. Take for example the case where one faction gives extra points on stun and another gives extra points on supply codes. I could switch between them before claiming, taking advantage of both instead of choosing the benefit/tradeoff I want. I admit this could still happen with players going to the supply, but it's at least harder for them to do so.

**Pull request merged**
